<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api;

use Magento\CatalogStorefrontApi\Proto\ProductsGetRequest;
use Magento\CatalogStorefrontApi\Proto\ProductsGetResult;
use Magento\CatalogStorefrontApi\Api\Data\ProductsGetRequestInterface;
use Magento\CatalogStorefrontApi\Api\Data\ProductsGetResultInterface;
use Magento\CatalogStorefrontApi\Proto\ImportProductsRequest;
use Magento\CatalogStorefrontApi\Proto\ImportProductsResponse;
use Magento\CatalogStorefrontApi\Api\Data\ImportProductsRequestInterface;
use Magento\CatalogStorefrontApi\Api\Data\ImportProductsResponseInterface;
use Magento\CatalogStorefrontApi\Proto\ImportCategoriesRequest;
use Magento\CatalogStorefrontApi\Proto\ImportCategoriesResponse;
use Magento\CatalogStorefrontApi\Api\Data\ImportCategoriesRequestInterface;
use Magento\CatalogStorefrontApi\Api\Data\ImportCategoriesResponseInterface;
use Magento\CatalogStorefrontApi\Proto\CategoriesGetRequest;
use Magento\CatalogStorefrontApi\Proto\CategoriesGetResponse;
use Magento\CatalogStorefrontApi\Api\Data\CategoriesGetRequestInterface;
use Magento\CatalogStorefrontApi\Api\Data\CategoriesGetResponseInterface;

/**
 * Autogenerated description for CatalogProxyServer class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 * @SuppressWarnings(PHPMD.UnusedFormalParameter)
 */
class CatalogProxyServer implements \Magento\CatalogStorefrontApi\Proto\CatalogInterface
{
    /**
     * @var CatalogServerInterface
     */
    private $service;

    /**
     * @param CatalogServerInterface $service
     */
    public function __construct(
        CatalogServerInterface $service
    ) {
        $this->service = $service;
    }

    /**
     * Autogenerated description for getProducts method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param ProductsGetRequest $in
     * @return ProductsGetResult
     */
    public function getProducts(\Spiral\GRPC\ContextInterface $ctx, ProductsGetRequest $in)
    : ProductsGetResult
    {
        try {
            $magentoDtoRequest = $this->getProductsFromProto($in);
            $magentoDtoResponse = $this->service->getProducts($magentoDtoRequest);
            return $this->getProductsToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for getProducts method
     *
     * @param ProductsGetRequest $value
     * @return ProductsGetRequestInterface
     */
    private function getProductsFromProto(ProductsGetRequest $value): ProductsGetRequestInterface
    {
        // convert data from \Magento\CatalogStorefrontApi\Proto\ProductsGetRequest
        // to \Magento\CatalogStorefrontApi\Api\Data\ProductsGetRequest
        /** @var \Magento\CatalogStorefrontApi\Proto\ProductsGetRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\CatalogStorefrontApi\Api\Data\ProductsGetRequest();
            $r->setIds($value->getIds());
            $r->setStore($value->getStore());
            $r->setAttributeCodes($value->getAttributeCodes());
            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for getProducts method
     *
     * @param ProductsGetResultInterface $value
     * @return ProductsGetResult
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function getProductsToProto(ProductsGetResultInterface $value): ProductsGetResult
    {
        // convert data from \Magento\CatalogStorefrontApi\Api\Data\ProductsGetResult
        // to \Magento\CatalogStorefrontApi\Proto\ProductsGetResult
        /** @var \Magento\CatalogStorefrontApi\Api\Data\ProductsGetResult $value **/
        $p = function () use ($value) {
            $r = new \Magento\CatalogStorefrontApi\Proto\ProductsGetResult();
            $res = [];
            foreach ($value->getItems() as $item) {
                // convert data from \Magento\CatalogStorefrontApi\Api\Data\Product
                // to \Magento\CatalogStorefrontApi\Proto\Product
                /** @var \Magento\CatalogStorefrontApi\Api\Data\Product $item **/
                $p = function () use ($item) {
                    $r = new \Magento\CatalogStorefrontApi\Proto\Product();
                    $r->setId($item->getId());
                    $r->setAttributeSetId($item->getAttributeSetId());
                    $r->setHasOptions($item->getHasOptions());
                    $r->setCreatedAt($item->getCreatedAt());
                    $r->setUpdatedAt($item->getUpdatedAt());
                    $r->setSku($item->getSku());
                    $r->setTypeId($item->getTypeId());
                    $r->setStatus($item->getStatus());
                    $r->setStockStatus($item->getStockStatus());
                    $r->setName($item->getName());
                    $r->setDescription($item->getDescription());
                    $r->setShortDescription($item->getShortDescription());
                    $r->setUrlKey($item->getUrlKey());
                    $r->setQty($item->getQty());
                    $r->setTaxClassId($item->getTaxClassId());
                    $r->setWeight($item->getWeight());
                    $prop18 = $item->getImage();
                    if ($prop18 !== null) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\Image
                        // to \Magento\CatalogStorefrontApi\Proto\Image
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\Image $prop18 **/
                        $p = function () use ($prop18) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\Image();
                            $r->setUrl($prop18->getUrl());
                            $r->setLabel($prop18->getLabel());
                            return $r;
                        };
                        $proto = $p();
                        $r->setImage($proto);
                    }

                    $prop19 = $item->getSmallImage();
                    if ($prop19 !== null) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\Image
                        // to \Magento\CatalogStorefrontApi\Proto\Image
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\Image $prop19 **/
                        $p = function () use ($prop19) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\Image();
                            $r->setUrl($prop19->getUrl());
                            $r->setLabel($prop19->getLabel());
                            return $r;
                        };
                        $proto = $p();
                        $r->setSmallImage($proto);
                    }

                    $prop20 = $item->getThumbnail();
                    if ($prop20 !== null) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\Image
                        // to \Magento\CatalogStorefrontApi\Proto\Image
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\Image $prop20 **/
                        $p = function () use ($prop20) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\Image();
                            $r->setUrl($prop20->getUrl());
                            $r->setLabel($prop20->getLabel());
                            return $r;
                        };
                        $proto = $p();
                        $r->setThumbnail($proto);
                    }

                    $r->setSwatchImage($item->getSwatchImage());
                    $res = [];
                    foreach ($item->getMediaGallery() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\MediaGalleryItem
                        // to \Magento\CatalogStorefrontApi\Proto\MediaGalleryItem
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\MediaGalleryItem $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\MediaGalleryItem();
                            $r->setUrl($item->getUrl());
                            $r->setLabel($item->getLabel());
                            $r->setMediaType($item->getMediaType());
                            $r->setPosition($item->getPosition());
                            $prop27 = $item->getVideoContent();
                            if ($prop27 !== null) {
                                // convert data from \Magento\CatalogStorefrontApi\Api\Data\Video
                                // to \Magento\CatalogStorefrontApi\Proto\Video
                                /** @var \Magento\CatalogStorefrontApi\Api\Data\Video $prop27 **/
                                $p = function () use ($prop27) {
                                    $r = new \Magento\CatalogStorefrontApi\Proto\Video();
                                    $r->setVideoProvider($prop27->getVideoProvider());
                                    $r->setVideoUrl($prop27->getVideoUrl());
                                    $r->setVideoTitle($prop27->getVideoTitle());
                                    $r->setVideoDescription($prop27->getVideoDescription());
                                    $r->setVideoMetadata($prop27->getVideoMetadata());
                                    $r->setMediaType($prop27->getMediaType());
                                    return $r;
                                };
                                $proto = $p();
                                $r->setVideoContent($proto);
                            }

                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setMediaGallery($res);

                    $r->setVisibility($item->getVisibility());
                    $res = [];
                    foreach ($item->getDynamicAttributes() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\DynamicAttributeValue
                        // to \Magento\CatalogStorefrontApi\Proto\DynamicAttributeValue
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\DynamicAttributeValue $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\DynamicAttributeValue();
                            $r->setCode($item->getCode());
                            $r->setValue($item->getValue());
                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setDynamicAttributes($res);

                    $r->setMetaDescription($item->getMetaDescription());
                    $r->setMetaKeyword($item->getMetaKeyword());
                    $r->setMetaTitle($item->getMetaTitle());
                    $r->setCategories($item->getCategories());
                    $r->setRequiredOptions($item->getRequiredOptions());
                    $r->setCreatedIn($item->getCreatedIn());
                    $r->setUpdatedIn($item->getUpdatedIn());
                    $r->setQuantityAndStockStatus($item->getQuantityAndStockStatus());
                    $r->setOptionsContainer($item->getOptionsContainer());
                    $r->setMsrpDisplayActualPriceType($item->getMsrpDisplayActualPriceType());
                    $r->setIsReturnable($item->getIsReturnable());
                    $r->setUrlSuffix($item->getUrlSuffix());
                    $res = [];
                    foreach ($item->getOptions() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\Option
                        // to \Magento\CatalogStorefrontApi\Proto\Option
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\Option $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\Option();
                            $r->setOptionId($item->getOptionId());
                            $r->setProductId($item->getProductId());
                            $r->setType($item->getType());
                            $r->setIsRequire($item->getIsRequire());
                            $r->setSku($item->getSku());
                            $r->setMaxCharacters($item->getMaxCharacters());
                            $r->setFileExtension($item->getFileExtension());
                            $r->setImageSizeX($item->getImageSizeX());
                            $r->setImageSizeY($item->getImageSizeY());
                            $r->setSortOrder($item->getSortOrder());
                            $r->setDefaultTitle($item->getDefaultTitle());
                            $r->setStoreTitle($item->getStoreTitle());
                            $r->setTitle($item->getTitle());
                            $r->setDefaultPrice($item->getDefaultPrice());
                            $r->setDefaultPriceType($item->getDefaultPriceType());
                            $r->setStorePrice($item->getStorePrice());
                            $r->setStorePriceType($item->getStorePriceType());
                            $r->setPrice($item->getPrice());
                            $r->setPriceType($item->getPriceType());
                            $r->setRequired($item->getRequired());
                            $r->setProductSku($item->getProductSku());
                            $res = [];
                            foreach ($item->getValue() as $item) {
                                // convert data from \Magento\CatalogStorefrontApi\Api\Data\OptionValue
                                // to \Magento\CatalogStorefrontApi\Proto\OptionValue
                                /** @var \Magento\CatalogStorefrontApi\Api\Data\OptionValue $item **/
                                $p = function () use ($item) {
                                    $r = new \Magento\CatalogStorefrontApi\Proto\OptionValue();
                                    $r->setOptionId($item->getOptionId());
                                    $r->setProductId($item->getProductId());
                                    $r->setType($item->getType());
                                    $r->setIsRequire($item->getIsRequire());
                                    $r->setSku($item->getSku());
                                    $r->setMaxCharacters($item->getMaxCharacters());
                                    $r->setFileExtension($item->getFileExtension());
                                    $r->setImageSizeX($item->getImageSizeX());
                                    $r->setImageSizeY($item->getImageSizeY());
                                    $r->setSortOrder($item->getSortOrder());
                                    $r->setDefaultTitle($item->getDefaultTitle());
                                    $r->setStoreTitle($item->getStoreTitle());
                                    $r->setTitle($item->getTitle());
                                    $r->setDefaultPrice($item->getDefaultPrice());
                                    $r->setDefaultPriceType($item->getDefaultPriceType());
                                    $r->setStorePrice($item->getStorePrice());
                                    $r->setStorePriceType($item->getStorePriceType());
                                    $r->setPrice($item->getPrice());
                                    $r->setPriceType($item->getPriceType());
                                    $r->setOptionTypeId($item->getOptionTypeId());
                                    return $r;
                                };
                                $proto = $p();
                                $res[] = $proto;
                            }
                            $r->setValue($res);

                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setOptions($res);

                    $res = [];
                    foreach ($item->getUrlRewrites() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\UrlRewrite
                        // to \Magento\CatalogStorefrontApi\Proto\UrlRewrite
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\UrlRewrite $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\UrlRewrite();
                            $r->setUrl($item->getUrl());
                            $res = [];
                            foreach ($item->getParameters() as $item) {
                                // convert data from \Magento\CatalogStorefrontApi\Api\Data\UrlRewriteParameter
                                // to \Magento\CatalogStorefrontApi\Proto\UrlRewriteParameter
                                /** @var \Magento\CatalogStorefrontApi\Api\Data\UrlRewriteParameter $item **/
                                $p = function () use ($item) {
                                    $r = new \Magento\CatalogStorefrontApi\Proto\UrlRewriteParameter();
                                    $r->setName($item->getName());
                                    $r->setValue($item->getValue());
                                    return $r;
                                };
                                $proto = $p();
                                $res[] = $proto;
                            }
                            $r->setParameters($res);

                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setUrlRewrites($res);

                    $res = [];
                    foreach ($item->getVariants() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\Variant
                        // to \Magento\CatalogStorefrontApi\Proto\Variant
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\Variant $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\Variant();
                            $r->setProduct($item->getProduct());
                            $res = [];
                            foreach ($item->getAttributes() as $item) {
                                // convert data from \Magento\CatalogStorefrontApi\Api\Data\VariantAttribute
                                // to \Magento\CatalogStorefrontApi\Proto\VariantAttribute
                                /** @var \Magento\CatalogStorefrontApi\Api\Data\VariantAttribute $item **/
                                $p = function () use ($item) {
                                    $r = new \Magento\CatalogStorefrontApi\Proto\VariantAttribute();
                                    $r->setLabel($item->getLabel());
                                    $r->setCode($item->getCode());
                                    $r->setValueIndex($item->getValueIndex());
                                    return $r;
                                };
                                $proto = $p();
                                $res[] = $proto;
                            }
                            $r->setAttributes($res);

                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setVariants($res);

                    $res = [];
                    foreach ($item->getConfigurableOptions() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\ConfigurableOption
                        // to \Magento\CatalogStorefrontApi\Proto\ConfigurableOption
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\ConfigurableOption $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\ConfigurableOption();
                            $r->setId($item->getId());
                            $r->setLabel($item->getLabel());
                            $r->setPosition($item->getPosition());
                            $r->setUseDefault($item->getUseDefault());
                            $r->setProductId($item->getProductId());
                            $r->setAttributeCode($item->getAttributeCode());
                            $r->setAttributeId($item->getAttributeId());
                            $res = [];
                            foreach ($item->getValues() as $item) {
                                // convert data from \Magento\CatalogStorefrontApi\Api\Data\ConfigurableOptionValue
                                // to \Magento\CatalogStorefrontApi\Proto\ConfigurableOptionValue
                                /** @var \Magento\CatalogStorefrontApi\Api\Data\ConfigurableOptionValue $item **/
                                $p = function () use ($item) {
                                    $r = new \Magento\CatalogStorefrontApi\Proto\ConfigurableOptionValue();
                                    $r->setValueIndex($item->getValueIndex());
                                    $r->setLabel($item->getLabel());
                                    $r->setDefaultLabel($item->getDefaultLabel());
                                    $r->setStoreLabel($item->getStoreLabel());
                                    $r->setUseDefaultValue($item->getUseDefaultValue());
                                    $r->setAttributeId($item->getAttributeId());
                                    $r->setProductId($item->getProductId());
                                    return $r;
                                };
                                $proto = $p();
                                $res[] = $proto;
                            }
                            $r->setValues($res);

                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setConfigurableOptions($res);

                    $r->setCountryOfManufacture($item->getCountryOfManufacture());
                    $r->setGiftMessageAvailable($item->getGiftMessageAvailable());
                    $r->setSpecialPrice($item->getSpecialPrice());
                    $r->setSpecialFromDate($item->getSpecialFromDate());
                    $r->setSpecialToDate($item->getSpecialToDate());
                    $res = [];
                    foreach ($item->getProductLinks() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\ProductLink
                        // to \Magento\CatalogStorefrontApi\Proto\ProductLink
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\ProductLink $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\ProductLink();
                            $r->setLinkedProductSku($item->getLinkedProductSku());
                            $r->setTypeId($item->getTypeId());
                            $r->setLinkedProductType($item->getLinkedProductType());
                            $r->setLinkTypeId($item->getLinkTypeId());
                            $r->setPosition($item->getPosition());
                            $r->setSku($item->getSku());
                            $r->setProductId($item->getProductId());
                            $r->setLinkType($item->getLinkType());
                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setProductLinks($res);

                    $r->setCanonicalUrl($item->getCanonicalUrl());
                    $r->setShipBundleItems($item->getShipBundleItems());
                    $r->setDynamicWeight($item->getDynamicWeight());
                    $r->setDynamicSku($item->getDynamicSku());
                    $r->setDynamicPrice($item->getDynamicPrice());
                    $r->setPriceView($item->getPriceView());
                    $res = [];
                    foreach ($item->getItems() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\BundleItem
                        // to \Magento\CatalogStorefrontApi\Proto\BundleItem
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\BundleItem $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\BundleItem();
                            $r->setOptionId($item->getOptionId());
                            $r->setTitle($item->getTitle());
                            $r->setRequired($item->getRequired());
                            $r->setType($item->getType());
                            $r->setPosition($item->getPosition());
                            $r->setSku($item->getSku());
                            $res = [];
                            foreach ($item->getOptions() as $item) {
                                // convert data from \Magento\CatalogStorefrontApi\Api\Data\BundleItemOption
                                // to \Magento\CatalogStorefrontApi\Proto\BundleItemOption
                                /** @var \Magento\CatalogStorefrontApi\Api\Data\BundleItemOption $item **/
                                $p = function () use ($item) {
                                    $r = new \Magento\CatalogStorefrontApi\Proto\BundleItemOption();
                                    $r->setId($item->getId());
                                    $r->setQuantity($item->getQuantity());
                                    $r->setIsDefault($item->getIsDefault());
                                    $r->setPrice($item->getPrice());
                                    $r->setPriceType($item->getPriceType());
                                    $r->setCanChangeQuantity($item->getCanChangeQuantity());
                                    $r->setLabel($item->getLabel());
                                    $r->setEntityId($item->getEntityId());
                                    $r->setPosition($item->getPosition());
                                    return $r;
                                };
                                $proto = $p();
                                $res[] = $proto;
                            }
                            $r->setOptions($res);

                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setItems($res);

                    $r->setLinksPurchasedSeparately($item->getLinksPurchasedSeparately());
                    $r->setLinksTitle($item->getLinksTitle());
                    $res = [];
                    foreach ($item->getDownloadableProductLinks() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\DownloadableLink
                        // to \Magento\CatalogStorefrontApi\Proto\DownloadableLink
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\DownloadableLink $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\DownloadableLink();
                            $r->setSampleUrl($item->getSampleUrl());
                            $r->setTitle($item->getTitle());
                            $r->setSortOrder($item->getSortOrder());
                            $r->setSampleType($item->getSampleType());
                            $r->setSampleFile($item->getSampleFile());
                            $r->setLinkId($item->getLinkId());
                            $r->setPrice($item->getPrice());
                            $r->setLinkType($item->getLinkType());
                            $r->setIsShareable($item->getIsShareable());
                            $r->setNumberOfDownloads($item->getNumberOfDownloads());
                            $r->setEntityId($item->getEntityId());
                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setDownloadableProductLinks($res);

                    $res = [];
                    foreach ($item->getDownloadableProductSamples() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\DownloadableSample
                        // to \Magento\CatalogStorefrontApi\Proto\DownloadableSample
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\DownloadableSample $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\DownloadableSample();
                            $r->setSampleUrl($item->getSampleUrl());
                            $r->setTitle($item->getTitle());
                            $r->setSortOrder($item->getSortOrder());
                            $r->setSampleType($item->getSampleType());
                            $r->setSampleFile($item->getSampleFile());
                            $r->setEntityId($item->getEntityId());
                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setDownloadableProductSamples($res);

                    return $r;
                };
                $proto = $p();
                $res[] = $proto;
            }
            $r->setItems($res);

            return $r;
        };
        $proto = $p();

        return $proto;
    }

    /**
     * Autogenerated description for importProducts method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param ImportProductsRequest $in
     * @return ImportProductsResponse
     */
    public function importProducts(\Spiral\GRPC\ContextInterface $ctx, ImportProductsRequest $in)
    : ImportProductsResponse
    {
        try {
            $magentoDtoRequest = $this->importProductsFromProto($in);
            $magentoDtoResponse = $this->service->importProducts($magentoDtoRequest);
            return $this->importProductsToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for importProducts method
     *
     * @param ImportProductsRequest $value
     * @return ImportProductsRequestInterface
     */
    private function importProductsFromProto(ImportProductsRequest $value): ImportProductsRequestInterface
    {
        // convert data from \Magento\CatalogStorefrontApi\Proto\ImportProductsRequest
        // to \Magento\CatalogStorefrontApi\Api\Data\ImportProductsRequest
        /** @var \Magento\CatalogStorefrontApi\Proto\ImportProductsRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\CatalogStorefrontApi\Api\Data\ImportProductsRequest();
            $res = [];
            foreach ($value->getProducts() as $item) {
                // convert data from \Magento\CatalogStorefrontApi\Proto\Product
                // to \Magento\CatalogStorefrontApi\Api\Data\Product
                /** @var \Magento\CatalogStorefrontApi\Proto\Product $item **/
                $p = function () use ($item) {
                    $r = new \Magento\CatalogStorefrontApi\Api\Data\Product();
                    $r->setId($item->getId());
                    $r->setAttributeSetId($item->getAttributeSetId());
                    $r->setHasOptions($item->getHasOptions());
                    $r->setCreatedAt($item->getCreatedAt());
                    $r->setUpdatedAt($item->getUpdatedAt());
                    $r->setSku($item->getSku());
                    $r->setTypeId($item->getTypeId());
                    $r->setStatus($item->getStatus());
                    $r->setStockStatus($item->getStockStatus());
                    $r->setName($item->getName());
                    $r->setDescription($item->getDescription());
                    $r->setShortDescription($item->getShortDescription());
                    $r->setUrlKey($item->getUrlKey());
                    $r->setQty($item->getQty());
                    $r->setTaxClassId($item->getTaxClassId());
                    $r->setWeight($item->getWeight());
                    $prop18 = $item->getImage();
                    if ($prop18 !== null) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\Image
                        // to \Magento\CatalogStorefrontApi\Api\Data\Image
                        /** @var \Magento\CatalogStorefrontApi\Proto\Image $prop18 **/
                        $p = function () use ($prop18) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\Image();
                            $r->setUrl($prop18->getUrl());
                            $r->setLabel($prop18->getLabel());
                            return $r;
                        };
                        $out = $p();
                        $r->setImage($out);
                    }

                    $prop19 = $item->getSmallImage();
                    if ($prop19 !== null) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\Image
                        // to \Magento\CatalogStorefrontApi\Api\Data\Image
                        /** @var \Magento\CatalogStorefrontApi\Proto\Image $prop19 **/
                        $p = function () use ($prop19) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\Image();
                            $r->setUrl($prop19->getUrl());
                            $r->setLabel($prop19->getLabel());
                            return $r;
                        };
                        $out = $p();
                        $r->setSmallImage($out);
                    }

                    $prop20 = $item->getThumbnail();
                    if ($prop20 !== null) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\Image
                        // to \Magento\CatalogStorefrontApi\Api\Data\Image
                        /** @var \Magento\CatalogStorefrontApi\Proto\Image $prop20 **/
                        $p = function () use ($prop20) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\Image();
                            $r->setUrl($prop20->getUrl());
                            $r->setLabel($prop20->getLabel());
                            return $r;
                        };
                        $out = $p();
                        $r->setThumbnail($out);
                    }

                    $r->setSwatchImage($item->getSwatchImage());
                    $res = [];
                    foreach ($item->getMediaGallery() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\MediaGalleryItem
                        // to \Magento\CatalogStorefrontApi\Api\Data\MediaGalleryItem
                        /** @var \Magento\CatalogStorefrontApi\Proto\MediaGalleryItem $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\MediaGalleryItem();
                            $r->setUrl($item->getUrl());
                            $r->setLabel($item->getLabel());
                            $r->setMediaType($item->getMediaType());
                            $r->setPosition($item->getPosition());
                            $prop27 = $item->getVideoContent();
                            if ($prop27 !== null) {
                                // convert data from \Magento\CatalogStorefrontApi\Proto\Video
                                // to \Magento\CatalogStorefrontApi\Api\Data\Video
                                /** @var \Magento\CatalogStorefrontApi\Proto\Video $prop27 **/
                                $p = function () use ($prop27) {
                                    $r = new \Magento\CatalogStorefrontApi\Api\Data\Video();
                                    $r->setVideoProvider($prop27->getVideoProvider());
                                    $r->setVideoUrl($prop27->getVideoUrl());
                                    $r->setVideoTitle($prop27->getVideoTitle());
                                    $r->setVideoDescription($prop27->getVideoDescription());
                                    $r->setVideoMetadata($prop27->getVideoMetadata());
                                    $r->setMediaType($prop27->getMediaType());
                                    return $r;
                                };
                                $out = $p();
                                $r->setVideoContent($out);
                            }

                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setMediaGallery($res);

                    $r->setVisibility($item->getVisibility());
                    $res = [];
                    foreach ($item->getDynamicAttributes() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\DynamicAttributeValue
                        // to \Magento\CatalogStorefrontApi\Api\Data\DynamicAttributeValue
                        /** @var \Magento\CatalogStorefrontApi\Proto\DynamicAttributeValue $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\DynamicAttributeValue();
                            $r->setCode($item->getCode());
                            $r->setValue($item->getValue());
                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setDynamicAttributes($res);

                    $r->setMetaDescription($item->getMetaDescription());
                    $r->setMetaKeyword($item->getMetaKeyword());
                    $r->setMetaTitle($item->getMetaTitle());
                    $r->setCategories($item->getCategories());
                    $r->setRequiredOptions($item->getRequiredOptions());
                    $r->setCreatedIn($item->getCreatedIn());
                    $r->setUpdatedIn($item->getUpdatedIn());
                    $r->setQuantityAndStockStatus($item->getQuantityAndStockStatus());
                    $r->setOptionsContainer($item->getOptionsContainer());
                    $r->setMsrpDisplayActualPriceType($item->getMsrpDisplayActualPriceType());
                    $r->setIsReturnable($item->getIsReturnable());
                    $r->setUrlSuffix($item->getUrlSuffix());
                    $res = [];
                    foreach ($item->getOptions() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\Option
                        // to \Magento\CatalogStorefrontApi\Api\Data\Option
                        /** @var \Magento\CatalogStorefrontApi\Proto\Option $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\Option();
                            $r->setOptionId($item->getOptionId());
                            $r->setProductId($item->getProductId());
                            $r->setType($item->getType());
                            $r->setIsRequire($item->getIsRequire());
                            $r->setSku($item->getSku());
                            $r->setMaxCharacters($item->getMaxCharacters());
                            $r->setFileExtension($item->getFileExtension());
                            $r->setImageSizeX($item->getImageSizeX());
                            $r->setImageSizeY($item->getImageSizeY());
                            $r->setSortOrder($item->getSortOrder());
                            $r->setDefaultTitle($item->getDefaultTitle());
                            $r->setStoreTitle($item->getStoreTitle());
                            $r->setTitle($item->getTitle());
                            $r->setDefaultPrice($item->getDefaultPrice());
                            $r->setDefaultPriceType($item->getDefaultPriceType());
                            $r->setStorePrice($item->getStorePrice());
                            $r->setStorePriceType($item->getStorePriceType());
                            $r->setPrice($item->getPrice());
                            $r->setPriceType($item->getPriceType());
                            $r->setRequired($item->getRequired());
                            $r->setProductSku($item->getProductSku());
                            $res = [];
                            foreach ($item->getValue() as $item) {
                                // convert data from \Magento\CatalogStorefrontApi\Proto\OptionValue
                                // to \Magento\CatalogStorefrontApi\Api\Data\OptionValue
                                /** @var \Magento\CatalogStorefrontApi\Proto\OptionValue $item **/
                                $p = function () use ($item) {
                                    $r = new \Magento\CatalogStorefrontApi\Api\Data\OptionValue();
                                    $r->setOptionId($item->getOptionId());
                                    $r->setProductId($item->getProductId());
                                    $r->setType($item->getType());
                                    $r->setIsRequire($item->getIsRequire());
                                    $r->setSku($item->getSku());
                                    $r->setMaxCharacters($item->getMaxCharacters());
                                    $r->setFileExtension($item->getFileExtension());
                                    $r->setImageSizeX($item->getImageSizeX());
                                    $r->setImageSizeY($item->getImageSizeY());
                                    $r->setSortOrder($item->getSortOrder());
                                    $r->setDefaultTitle($item->getDefaultTitle());
                                    $r->setStoreTitle($item->getStoreTitle());
                                    $r->setTitle($item->getTitle());
                                    $r->setDefaultPrice($item->getDefaultPrice());
                                    $r->setDefaultPriceType($item->getDefaultPriceType());
                                    $r->setStorePrice($item->getStorePrice());
                                    $r->setStorePriceType($item->getStorePriceType());
                                    $r->setPrice($item->getPrice());
                                    $r->setPriceType($item->getPriceType());
                                    $r->setOptionTypeId($item->getOptionTypeId());
                                    return $r;
                                };
                                $out = $p();
                                $res[] = $out;
                            }
                            $r->setValue($res);

                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setOptions($res);

                    $res = [];
                    foreach ($item->getUrlRewrites() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\UrlRewrite
                        // to \Magento\CatalogStorefrontApi\Api\Data\UrlRewrite
                        /** @var \Magento\CatalogStorefrontApi\Proto\UrlRewrite $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\UrlRewrite();
                            $r->setUrl($item->getUrl());
                            $res = [];
                            foreach ($item->getParameters() as $item) {
                                // convert data from \Magento\CatalogStorefrontApi\Proto\UrlRewriteParameter
                                // to \Magento\CatalogStorefrontApi\Api\Data\UrlRewriteParameter
                                /** @var \Magento\CatalogStorefrontApi\Proto\UrlRewriteParameter $item **/
                                $p = function () use ($item) {
                                    $r = new \Magento\CatalogStorefrontApi\Api\Data\UrlRewriteParameter();
                                    $r->setName($item->getName());
                                    $r->setValue($item->getValue());
                                    return $r;
                                };
                                $out = $p();
                                $res[] = $out;
                            }
                            $r->setParameters($res);

                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setUrlRewrites($res);

                    $res = [];
                    foreach ($item->getVariants() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\Variant
                        // to \Magento\CatalogStorefrontApi\Api\Data\Variant
                        /** @var \Magento\CatalogStorefrontApi\Proto\Variant $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\Variant();
                            $r->setProduct($item->getProduct());
                            $res = [];
                            foreach ($item->getAttributes() as $item) {
                                // convert data from \Magento\CatalogStorefrontApi\Proto\VariantAttribute
                                // to \Magento\CatalogStorefrontApi\Api\Data\VariantAttribute
                                /** @var \Magento\CatalogStorefrontApi\Proto\VariantAttribute $item **/
                                $p = function () use ($item) {
                                    $r = new \Magento\CatalogStorefrontApi\Api\Data\VariantAttribute();
                                    $r->setLabel($item->getLabel());
                                    $r->setCode($item->getCode());
                                    $r->setValueIndex($item->getValueIndex());
                                    return $r;
                                };
                                $out = $p();
                                $res[] = $out;
                            }
                            $r->setAttributes($res);

                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setVariants($res);

                    $res = [];
                    foreach ($item->getConfigurableOptions() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\ConfigurableOption
                        // to \Magento\CatalogStorefrontApi\Api\Data\ConfigurableOption
                        /** @var \Magento\CatalogStorefrontApi\Proto\ConfigurableOption $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\ConfigurableOption();
                            $r->setId($item->getId());
                            $r->setLabel($item->getLabel());
                            $r->setPosition($item->getPosition());
                            $r->setUseDefault($item->getUseDefault());
                            $r->setProductId($item->getProductId());
                            $r->setAttributeCode($item->getAttributeCode());
                            $r->setAttributeId($item->getAttributeId());
                            $res = [];
                            foreach ($item->getValues() as $item) {
                                // convert data from \Magento\CatalogStorefrontApi\Proto\ConfigurableOptionValue
                                // to \Magento\CatalogStorefrontApi\Api\Data\ConfigurableOptionValue
                                /** @var \Magento\CatalogStorefrontApi\Proto\ConfigurableOptionValue $item **/
                                $p = function () use ($item) {
                                    $r = new \Magento\CatalogStorefrontApi\Api\Data\ConfigurableOptionValue();
                                    $r->setValueIndex($item->getValueIndex());
                                    $r->setLabel($item->getLabel());
                                    $r->setDefaultLabel($item->getDefaultLabel());
                                    $r->setStoreLabel($item->getStoreLabel());
                                    $r->setUseDefaultValue($item->getUseDefaultValue());
                                    $r->setAttributeId($item->getAttributeId());
                                    $r->setProductId($item->getProductId());
                                    return $r;
                                };
                                $out = $p();
                                $res[] = $out;
                            }
                            $r->setValues($res);

                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setConfigurableOptions($res);

                    $r->setCountryOfManufacture($item->getCountryOfManufacture());
                    $r->setGiftMessageAvailable($item->getGiftMessageAvailable());
                    $r->setSpecialPrice($item->getSpecialPrice());
                    $r->setSpecialFromDate($item->getSpecialFromDate());
                    $r->setSpecialToDate($item->getSpecialToDate());
                    $res = [];
                    foreach ($item->getProductLinks() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\ProductLink
                        // to \Magento\CatalogStorefrontApi\Api\Data\ProductLink
                        /** @var \Magento\CatalogStorefrontApi\Proto\ProductLink $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\ProductLink();
                            $r->setLinkedProductSku($item->getLinkedProductSku());
                            $r->setTypeId($item->getTypeId());
                            $r->setLinkedProductType($item->getLinkedProductType());
                            $r->setLinkTypeId($item->getLinkTypeId());
                            $r->setPosition($item->getPosition());
                            $r->setSku($item->getSku());
                            $r->setProductId($item->getProductId());
                            $r->setLinkType($item->getLinkType());
                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setProductLinks($res);

                    $r->setCanonicalUrl($item->getCanonicalUrl());
                    $r->setShipBundleItems($item->getShipBundleItems());
                    $r->setDynamicWeight($item->getDynamicWeight());
                    $r->setDynamicSku($item->getDynamicSku());
                    $r->setDynamicPrice($item->getDynamicPrice());
                    $r->setPriceView($item->getPriceView());
                    $res = [];
                    foreach ($item->getItems() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\BundleItem
                        // to \Magento\CatalogStorefrontApi\Api\Data\BundleItem
                        /** @var \Magento\CatalogStorefrontApi\Proto\BundleItem $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\BundleItem();
                            $r->setOptionId($item->getOptionId());
                            $r->setTitle($item->getTitle());
                            $r->setRequired($item->getRequired());
                            $r->setType($item->getType());
                            $r->setPosition($item->getPosition());
                            $r->setSku($item->getSku());
                            $res = [];
                            foreach ($item->getOptions() as $item) {
                                // convert data from \Magento\CatalogStorefrontApi\Proto\BundleItemOption
                                // to \Magento\CatalogStorefrontApi\Api\Data\BundleItemOption
                                /** @var \Magento\CatalogStorefrontApi\Proto\BundleItemOption $item **/
                                $p = function () use ($item) {
                                    $r = new \Magento\CatalogStorefrontApi\Api\Data\BundleItemOption();
                                    $r->setId($item->getId());
                                    $r->setQuantity($item->getQuantity());
                                    $r->setIsDefault($item->getIsDefault());
                                    $r->setPrice($item->getPrice());
                                    $r->setPriceType($item->getPriceType());
                                    $r->setCanChangeQuantity($item->getCanChangeQuantity());
                                    $r->setLabel($item->getLabel());
                                    $r->setEntityId($item->getEntityId());
                                    $r->setPosition($item->getPosition());
                                    return $r;
                                };
                                $out = $p();
                                $res[] = $out;
                            }
                            $r->setOptions($res);

                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setItems($res);

                    $r->setLinksPurchasedSeparately($item->getLinksPurchasedSeparately());
                    $r->setLinksTitle($item->getLinksTitle());
                    $res = [];
                    foreach ($item->getDownloadableProductLinks() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\DownloadableLink
                        // to \Magento\CatalogStorefrontApi\Api\Data\DownloadableLink
                        /** @var \Magento\CatalogStorefrontApi\Proto\DownloadableLink $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\DownloadableLink();
                            $r->setSampleUrl($item->getSampleUrl());
                            $r->setTitle($item->getTitle());
                            $r->setSortOrder($item->getSortOrder());
                            $r->setSampleType($item->getSampleType());
                            $r->setSampleFile($item->getSampleFile());
                            $r->setLinkId($item->getLinkId());
                            $r->setPrice($item->getPrice());
                            $r->setLinkType($item->getLinkType());
                            $r->setIsShareable($item->getIsShareable());
                            $r->setNumberOfDownloads($item->getNumberOfDownloads());
                            $r->setEntityId($item->getEntityId());
                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setDownloadableProductLinks($res);

                    $res = [];
                    foreach ($item->getDownloadableProductSamples() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\DownloadableSample
                        // to \Magento\CatalogStorefrontApi\Api\Data\DownloadableSample
                        /** @var \Magento\CatalogStorefrontApi\Proto\DownloadableSample $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\DownloadableSample();
                            $r->setSampleUrl($item->getSampleUrl());
                            $r->setTitle($item->getTitle());
                            $r->setSortOrder($item->getSortOrder());
                            $r->setSampleType($item->getSampleType());
                            $r->setSampleFile($item->getSampleFile());
                            $r->setEntityId($item->getEntityId());
                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setDownloadableProductSamples($res);

                    return $r;
                };
                $out = $p();
                $res[] = $out;
            }
            $r->setProducts($res);

            $r->setStore($value->getStore());
            $prop3 = $value->getParams();
            if ($prop3 !== null) {
                // convert data from \Magento\CatalogStorefrontApi\Proto\KeyValue
                // to \Magento\CatalogStorefrontApi\Api\Data\KeyValue
                /** @var \Magento\CatalogStorefrontApi\Proto\KeyValue $prop3 **/
                $p = function () use ($prop3) {
                    $r = new \Magento\CatalogStorefrontApi\Api\Data\KeyValue();
                    $r->setKey($prop3->getKey());
                    $r->setValue($prop3->getValue());
                    return $r;
                };
                $out = $p();
                $r->setParams($out);
            }

            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for importProducts method
     *
     * @param ImportProductsResponseInterface $value
     * @return ImportProductsResponse
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function importProductsToProto(ImportProductsResponseInterface $value): ImportProductsResponse
    {
        // convert data from \Magento\CatalogStorefrontApi\Api\Data\ImportProductsResponse
        // to \Magento\CatalogStorefrontApi\Proto\ImportProductsResponse
        /** @var \Magento\CatalogStorefrontApi\Api\Data\ImportProductsResponse $value **/
        $p = function () use ($value) {
            $r = new \Magento\CatalogStorefrontApi\Proto\ImportProductsResponse();
            $r->setStatus($value->getStatus());
            $r->setMessage($value->getMessage());
            return $r;
        };
        $proto = $p();

        return $proto;
    }

    /**
     * Autogenerated description for importCategories method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param ImportCategoriesRequest $in
     * @return ImportCategoriesResponse
     */
    public function importCategories(\Spiral\GRPC\ContextInterface $ctx, ImportCategoriesRequest $in)
    : ImportCategoriesResponse
    {
        try {
            $magentoDtoRequest = $this->importCategoriesFromProto($in);
            $magentoDtoResponse = $this->service->importCategories($magentoDtoRequest);
            return $this->importCategoriesToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for importCategories method
     *
     * @param ImportCategoriesRequest $value
     * @return ImportCategoriesRequestInterface
     */
    private function importCategoriesFromProto(ImportCategoriesRequest $value): ImportCategoriesRequestInterface
    {
        // convert data from \Magento\CatalogStorefrontApi\Proto\ImportCategoriesRequest
        // to \Magento\CatalogStorefrontApi\Api\Data\ImportCategoriesRequest
        /** @var \Magento\CatalogStorefrontApi\Proto\ImportCategoriesRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\CatalogStorefrontApi\Api\Data\ImportCategoriesRequest();
            $res = [];
            foreach ($value->getCategories() as $item) {
                // convert data from \Magento\CatalogStorefrontApi\Proto\Category
                // to \Magento\CatalogStorefrontApi\Api\Data\Category
                /** @var \Magento\CatalogStorefrontApi\Proto\Category $item **/
                $p = function () use ($item) {
                    $r = new \Magento\CatalogStorefrontApi\Api\Data\Category();
                    $r->setId($item->getId());
                    $r->setPath($item->getPath());
                    $r->setPosition($item->getPosition());
                    $r->setLevel($item->getLevel());
                    $r->setChildrenCount($item->getChildrenCount());
                    $r->setName($item->getName());
                    $r->setDisplayMode($item->getDisplayMode());
                    $r->setDefaultSortBy($item->getDefaultSortBy());
                    $r->setUrlKey($item->getUrlKey());
                    $r->setUrlPath($item->getUrlPath());
                    $r->setIsActive($item->getIsActive());
                    $r->setIsAnchor($item->getIsAnchor());
                    $r->setIncludeInMenu($item->getIncludeInMenu());
                    $r->setAvailableSortBy($item->getAvailableSortBy());
                    $res = [];
                    foreach ($item->getBreadcrumbs() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\Breadcrumb
                        // to \Magento\CatalogStorefrontApi\Api\Data\Breadcrumb
                        /** @var \Magento\CatalogStorefrontApi\Proto\Breadcrumb $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\Breadcrumb();
                            $r->setCategoryId($item->getCategoryId());
                            $r->setCategoryName($item->getCategoryName());
                            $r->setCategoryLevel($item->getCategoryLevel());
                            $r->setCategoryUrlKey($item->getCategoryUrlKey());
                            $r->setCategoryUrlPath($item->getCategoryUrlPath());
                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setBreadcrumbs($res);

                    $r->setDescription($item->getDescription());
                    $r->setCanonicalUrl($item->getCanonicalUrl());
                    $r->setProductCount($item->getProductCount());
                    $r->setChildren($item->getChildren());
                    $r->setImage($item->getImage());
                    $r->setParentId($item->getParentId());
                    $r->setMetaTitle($item->getMetaTitle());
                    $r->setMetaDescription($item->getMetaDescription());
                    $r->setMetaKeywords($item->getMetaKeywords());
                    $res = [];
                    foreach ($item->getDynamicAttributes() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Proto\DynamicAttributeValue
                        // to \Magento\CatalogStorefrontApi\Api\Data\DynamicAttributeValue
                        /** @var \Magento\CatalogStorefrontApi\Proto\DynamicAttributeValue $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Api\Data\DynamicAttributeValue();
                            $r->setCode($item->getCode());
                            $r->setValue($item->getValue());
                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setDynamicAttributes($res);

                    return $r;
                };
                $out = $p();
                $res[] = $out;
            }
            $r->setCategories($res);

            $r->setStore($value->getStore());
            $prop3 = $value->getParams();
            if ($prop3 !== null) {
                // convert data from \Magento\CatalogStorefrontApi\Proto\KeyValue
                // to \Magento\CatalogStorefrontApi\Api\Data\KeyValue
                /** @var \Magento\CatalogStorefrontApi\Proto\KeyValue $prop3 **/
                $p = function () use ($prop3) {
                    $r = new \Magento\CatalogStorefrontApi\Api\Data\KeyValue();
                    $r->setKey($prop3->getKey());
                    $r->setValue($prop3->getValue());
                    return $r;
                };
                $out = $p();
                $r->setParams($out);
            }

            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for importCategories method
     *
     * @param ImportCategoriesResponseInterface $value
     * @return ImportCategoriesResponse
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function importCategoriesToProto(ImportCategoriesResponseInterface $value): ImportCategoriesResponse
    {
        // convert data from \Magento\CatalogStorefrontApi\Api\Data\ImportCategoriesResponse
        // to \Magento\CatalogStorefrontApi\Proto\ImportCategoriesResponse
        /** @var \Magento\CatalogStorefrontApi\Api\Data\ImportCategoriesResponse $value **/
        $p = function () use ($value) {
            $r = new \Magento\CatalogStorefrontApi\Proto\ImportCategoriesResponse();
            $r->setStatus($value->getStatus());
            $r->setMessage($value->getMessage());
            return $r;
        };
        $proto = $p();

        return $proto;
    }

    /**
     * Autogenerated description for getCategories method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param CategoriesGetRequest $in
     * @return CategoriesGetResponse
     */
    public function getCategories(\Spiral\GRPC\ContextInterface $ctx, CategoriesGetRequest $in)
    : CategoriesGetResponse
    {
        try {
            $magentoDtoRequest = $this->getCategoriesFromProto($in);
            $magentoDtoResponse = $this->service->getCategories($magentoDtoRequest);
            return $this->getCategoriesToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for getCategories method
     *
     * @param CategoriesGetRequest $value
     * @return CategoriesGetRequestInterface
     */
    private function getCategoriesFromProto(CategoriesGetRequest $value): CategoriesGetRequestInterface
    {
        // convert data from \Magento\CatalogStorefrontApi\Proto\CategoriesGetRequest
        // to \Magento\CatalogStorefrontApi\Api\Data\CategoriesGetRequest
        /** @var \Magento\CatalogStorefrontApi\Proto\CategoriesGetRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\CatalogStorefrontApi\Api\Data\CategoriesGetRequest();
            $r->setIds($value->getIds());
            $r->setLevel($value->getLevel());
            $r->setStore($value->getStore());
            $r->setAttributeCodes($value->getAttributeCodes());
            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for getCategories method
     *
     * @param CategoriesGetResponseInterface $value
     * @return CategoriesGetResponse
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function getCategoriesToProto(CategoriesGetResponseInterface $value): CategoriesGetResponse
    {
        // convert data from \Magento\CatalogStorefrontApi\Api\Data\CategoriesGetResponse
        // to \Magento\CatalogStorefrontApi\Proto\CategoriesGetResponse
        /** @var \Magento\CatalogStorefrontApi\Api\Data\CategoriesGetResponse $value **/
        $p = function () use ($value) {
            $r = new \Magento\CatalogStorefrontApi\Proto\CategoriesGetResponse();
            $res = [];
            foreach ($value->getItems() as $item) {
                // convert data from \Magento\CatalogStorefrontApi\Api\Data\Category
                // to \Magento\CatalogStorefrontApi\Proto\Category
                /** @var \Magento\CatalogStorefrontApi\Api\Data\Category $item **/
                $p = function () use ($item) {
                    $r = new \Magento\CatalogStorefrontApi\Proto\Category();
                    $r->setId($item->getId());
                    $r->setPath($item->getPath());
                    $r->setPosition($item->getPosition());
                    $r->setLevel($item->getLevel());
                    $r->setChildrenCount($item->getChildrenCount());
                    $r->setName($item->getName());
                    $r->setDisplayMode($item->getDisplayMode());
                    $r->setDefaultSortBy($item->getDefaultSortBy());
                    $r->setUrlKey($item->getUrlKey());
                    $r->setUrlPath($item->getUrlPath());
                    $r->setIsActive($item->getIsActive());
                    $r->setIsAnchor($item->getIsAnchor());
                    $r->setIncludeInMenu($item->getIncludeInMenu());
                    $r->setAvailableSortBy($item->getAvailableSortBy());
                    $res = [];
                    foreach ($item->getBreadcrumbs() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\Breadcrumb
                        // to \Magento\CatalogStorefrontApi\Proto\Breadcrumb
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\Breadcrumb $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\Breadcrumb();
                            $r->setCategoryId($item->getCategoryId());
                            $r->setCategoryName($item->getCategoryName());
                            $r->setCategoryLevel($item->getCategoryLevel());
                            $r->setCategoryUrlKey($item->getCategoryUrlKey());
                            $r->setCategoryUrlPath($item->getCategoryUrlPath());
                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setBreadcrumbs($res);

                    $r->setDescription($item->getDescription());
                    $r->setCanonicalUrl($item->getCanonicalUrl());
                    $r->setProductCount($item->getProductCount());
                    $r->setChildren($item->getChildren());
                    $r->setImage($item->getImage());
                    $r->setParentId($item->getParentId());
                    $r->setMetaTitle($item->getMetaTitle());
                    $r->setMetaDescription($item->getMetaDescription());
                    $r->setMetaKeywords($item->getMetaKeywords());
                    $res = [];
                    foreach ($item->getDynamicAttributes() as $item) {
                        // convert data from \Magento\CatalogStorefrontApi\Api\Data\DynamicAttributeValue
                        // to \Magento\CatalogStorefrontApi\Proto\DynamicAttributeValue
                        /** @var \Magento\CatalogStorefrontApi\Api\Data\DynamicAttributeValue $item **/
                        $p = function () use ($item) {
                            $r = new \Magento\CatalogStorefrontApi\Proto\DynamicAttributeValue();
                            $r->setCode($item->getCode());
                            $r->setValue($item->getValue());
                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setDynamicAttributes($res);

                    return $r;
                };
                $proto = $p();
                $res[] = $proto;
            }
            $r->setItems($res);

            return $r;
        };
        $proto = $p();

        return $proto;
    }
}
