<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api;

use \Magento\CatalogStorefrontApi\Api\Data\ImportVariantsRequestInterface;
use \Magento\CatalogStorefrontApi\Api\Data\ImportVariantsResponseInterface;
use \Magento\CatalogStorefrontApi\Api\Data\DeleteVariantsRequestInterface;
use \Magento\CatalogStorefrontApi\Api\Data\DeleteVariantsResponseInterface;
use \Magento\CatalogStorefrontApi\Api\Data\ProductVariantRequestInterface;
use \Magento\CatalogStorefrontApi\Api\Data\ProductVariantResponseInterface;
use \Magento\CatalogStorefrontApi\Api\Data\OptionSelectionRequestInterface;

/**
 * Autogenerated description for VariantServiceInterface interface
 */
interface VariantServiceInterface
{
    /**
     * Autogenerated description for importProductVariants interface method
     *
     * @param ImportVariantsRequestInterface $request
     * @return ImportVariantsResponseInterface
     * @throws \Throwable
     */
    public function importProductVariants(ImportVariantsRequestInterface $request): ImportVariantsResponseInterface;

    /**
     * Autogenerated description for deleteProductVariants interface method
     *
     * @param DeleteVariantsRequestInterface $request
     * @return DeleteVariantsResponseInterface
     * @throws \Throwable
     */
    public function deleteProductVariants(DeleteVariantsRequestInterface $request): DeleteVariantsResponseInterface;

    /**
     * Autogenerated description for getProductVariants interface method
     *
     * @param ProductVariantRequestInterface $request
     * @return ProductVariantResponseInterface
     * @throws \Throwable
     */
    public function getProductVariants(ProductVariantRequestInterface $request): ProductVariantResponseInterface;

    /**
     * Autogenerated description for getVariantsMatch interface method
     *
     * @param OptionSelectionRequestInterface $request
     * @return ProductVariantResponseInterface
     * @throws \Throwable
     */
    public function getVariantsMatch(OptionSelectionRequestInterface $request): ProductVariantResponseInterface;

    /**
     * Autogenerated description for getVariantsExactlyMatch interface method
     *
     * @param OptionSelectionRequestInterface $request
     * @return ProductVariantResponseInterface
     * @throws \Throwable
     */
    public function getVariantsExactlyMatch(OptionSelectionRequestInterface $request): ProductVariantResponseInterface;

    /**
     * Autogenerated description for getVariantsInclude interface method
     *
     * @param OptionSelectionRequestInterface $request
     * @return ProductVariantResponseInterface
     * @throws \Throwable
     */
    public function getVariantsInclude(OptionSelectionRequestInterface $request): ProductVariantResponseInterface;
}
