<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

final class Breadcrumb implements BreadcrumbInterface
{
    /**
     * @var string
     */
    private $categoryId;
    /**
     * @var string
     */
    private $categoryName;
    /**
     * @var int
     */
    private $categoryLevel;
    /**
     * @var string
     */
    private $categoryUrlKey;
    /**
     * @var string
     */
    private $categoryUrlPath;


    /**
     * @return string
     */
    public function getCategoryId(): string
    {
        return (string) $this->categoryId;
    }
    
    /**
     * @param string $value
     * @return void
     */
    public function setCategoryId(string $value): void
    {
        $this->categoryId = $value;
    }

    /**
     * @return string
     */
    public function getCategoryName(): string
    {
        return (string) $this->categoryName;
    }
    
    /**
     * @param string $value
     * @return void
     */
    public function setCategoryName(string $value): void
    {
        $this->categoryName = $value;
    }

    /**
     * @return int
     */
    public function getCategoryLevel(): int
    {
        return (int) $this->categoryLevel;
    }
    
    /**
     * @param int $value
     * @return void
     */
    public function setCategoryLevel(int $value): void
    {
        $this->categoryLevel = $value;
    }

    /**
     * @return string
     */
    public function getCategoryUrlKey(): string
    {
        return (string) $this->categoryUrlKey;
    }
    
    /**
     * @param string $value
     * @return void
     */
    public function setCategoryUrlKey(string $value): void
    {
        $this->categoryUrlKey = $value;
    }

    /**
     * @return string
     */
    public function getCategoryUrlPath(): string
    {
        return (string) $this->categoryUrlPath;
    }
    
    /**
     * @param string $value
     * @return void
     */
    public function setCategoryUrlPath(string $value): void
    {
        $this->categoryUrlPath = $value;
    }
}
