<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for Breadcrumb interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface BreadcrumbInterface
{
    /**
     * Autogenerated description for getCategoryId() interface method
     *
     * @return string
     */
    public function getCategoryId(): string;

    /**
     * Autogenerated description for setCategoryId() interface method
     *
     * @param string $value
     * @return void
     */
    public function setCategoryId(string $value): void;

    /**
     * Autogenerated description for getCategoryName() interface method
     *
     * @return string
     */
    public function getCategoryName(): string;

    /**
     * Autogenerated description for setCategoryName() interface method
     *
     * @param string $value
     * @return void
     */
    public function setCategoryName(string $value): void;

    /**
     * Autogenerated description for getCategoryLevel() interface method
     *
     * @return int
     */
    public function getCategoryLevel(): int;

    /**
     * Autogenerated description for setCategoryLevel() interface method
     *
     * @param int $value
     * @return void
     */
    public function setCategoryLevel(int $value): void;

    /**
     * Autogenerated description for getCategoryUrlKey() interface method
     *
     * @return string
     */
    public function getCategoryUrlKey(): string;

    /**
     * Autogenerated description for setCategoryUrlKey() interface method
     *
     * @param string $value
     * @return void
     */
    public function setCategoryUrlKey(string $value): void;

    /**
     * Autogenerated description for getCategoryUrlPath() interface method
     *
     * @return string
     */
    public function getCategoryUrlPath(): string;

    /**
     * Autogenerated description for setCategoryUrlPath() interface method
     *
     * @param string $value
     * @return void
     */
    public function setCategoryUrlPath(string $value): void;
}
