<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

final class BundleItem implements BundleItemInterface
{
    /**
     * @var string
     */
    private $optionId;
    /**
     * @var string
     */
    private $title;
    /**
     * @var bool
     */
    private $required;
    /**
     * @var string
     */
    private $type;
    /**
     * @var int
     */
    private $position;
    /**
     * @var string
     */
    private $sku;
    /**
     * @var array
     */
    private $options;


    /**
     * @return string
     */
    public function getOptionId(): string
    {
        return (string) $this->optionId;
    }
    
    /**
     * @param string $value
     * @return void
     */
    public function setOptionId(string $value): void
    {
        $this->optionId = $value;
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return (string) $this->title;
    }
    
    /**
     * @param string $value
     * @return void
     */
    public function setTitle(string $value): void
    {
        $this->title = $value;
    }

    /**
     * @return bool
     */
    public function getRequired(): bool
    {
        return (bool) $this->required;
    }
    
    /**
     * @param bool $value
     * @return void
     */
    public function setRequired(bool $value): void
    {
        $this->required = $value;
    }

    /**
     * @return string
     */
    public function getType(): string
    {
        return (string) $this->type;
    }
    
    /**
     * @param string $value
     * @return void
     */
    public function setType(string $value): void
    {
        $this->type = $value;
    }

    /**
     * @return int
     */
    public function getPosition(): int
    {
        return (int) $this->position;
    }
    
    /**
     * @param int $value
     * @return void
     */
    public function setPosition(int $value): void
    {
        $this->position = $value;
    }

    /**
     * @return string
     */
    public function getSku(): string
    {
        return (string) $this->sku;
    }
    
    /**
     * @param string $value
     * @return void
     */
    public function setSku(string $value): void
    {
        $this->sku = $value;
    }

    /**
     * @return \Magento\CatalogStorefrontApi\Api\Data\BundleItemOptionInterface[]
     */
    public function getOptions(): array
    {
        return (array) $this->options;
    }
    
    /**
     * @param \Magento\CatalogStorefrontApi\Api\Data\BundleItemOptionInterface[] $value
     * @return void
     */
    public function setOptions(array $value): void
    {
        $this->options = $value;
    }
}
