<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for BundleItem interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface BundleItemInterface
{
    /**
     * Autogenerated description for getOptionId() interface method
     *
     * @return string
     */
    public function getOptionId(): string;

    /**
     * Autogenerated description for setOptionId() interface method
     *
     * @param string $value
     * @return void
     */
    public function setOptionId(string $value): void;

    /**
     * Autogenerated description for getTitle() interface method
     *
     * @return string
     */
    public function getTitle(): string;

    /**
     * Autogenerated description for setTitle() interface method
     *
     * @param string $value
     * @return void
     */
    public function setTitle(string $value): void;

    /**
     * Autogenerated description for getRequired() interface method
     *
     * @return bool
     */
    public function getRequired(): bool;

    /**
     * Autogenerated description for setRequired() interface method
     *
     * @param bool $value
     * @return void
     */
    public function setRequired(bool $value): void;

    /**
     * Autogenerated description for getType() interface method
     *
     * @return string
     */
    public function getType(): string;

    /**
     * Autogenerated description for setType() interface method
     *
     * @param string $value
     * @return void
     */
    public function setType(string $value): void;

    /**
     * Autogenerated description for getPosition() interface method
     *
     * @return int
     */
    public function getPosition(): int;

    /**
     * Autogenerated description for setPosition() interface method
     *
     * @param int $value
     * @return void
     */
    public function setPosition(int $value): void;

    /**
     * Autogenerated description for getSku() interface method
     *
     * @return string
     */
    public function getSku(): string;

    /**
     * Autogenerated description for setSku() interface method
     *
     * @param string $value
     * @return void
     */
    public function setSku(string $value): void;

    /**
     * Autogenerated description for getOptions() interface method
     *
     * @return \Magento\CatalogStorefrontApi\Api\Data\BundleItemOptionInterface[]
     */
    public function getOptions(): array;

    /**
     * Autogenerated description for setOptions() interface method
     *
     * @param \Magento\CatalogStorefrontApi\Api\Data\BundleItemOptionInterface[] $value
     * @return void
     */
    public function setOptions(array $value): void;
}
