<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

final class CategoriesGetResponse implements CategoriesGetResponseInterface
{
    /**
     * @var array
     */
    private $items;


    /**
     * @return \Magento\CatalogStorefrontApi\Api\Data\CategoryInterface[]
     */
    public function getItems(): array
    {
        return (array) $this->items;
    }
    
    /**
     * @param \Magento\CatalogStorefrontApi\Api\Data\CategoryInterface[] $value
     * @return void
     */
    public function setItems(array $value): void
    {
        $this->items = $value;
    }
}
