<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

use Magento\Framework\ObjectManagerInterface;

/**
 * Autogenerated description for DownloadableSample class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.UnusedPrivateField)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
final class DownloadableSampleArrayMapper
{
    /**
     * @var mixed
     */
    private $data;

    /**
     * @var ObjectManagerInterface
     */
    private $objectManager;

    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
    }

    /**
    * Convert the DTO to the array with the data
    *
    * @param DownloadableSample $dto
    * @return array
    */
    public function convertToArray(DownloadableSample $dto)
    {
        $result = [];
        $result["sample_url"] = $dto->getSampleUrl();
        $result["title"] = $dto->getTitle();
        $result["sort_order"] = $dto->getSortOrder();
        $result["sample_type"] = $dto->getSampleType();
        $result["sample_file"] = $dto->getSampleFile();
        $result["entity_id"] = $dto->getEntityId();
        return $result;
    }
}
