<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for Image interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ImageInterface
{
    /**
     * Autogenerated description for getResource() interface method
     *
     * @return \Magento\CatalogStorefrontApi\Api\Data\MediaResourceInterface|null
     */
    public function getResource(): ?\Magento\CatalogStorefrontApi\Api\Data\MediaResourceInterface;

    /**
     * Autogenerated description for setResource() interface method
     *
     * @param \Magento\CatalogStorefrontApi\Api\Data\MediaResourceInterface $value
     * @return void
     */
    public function setResource(\Magento\CatalogStorefrontApi\Api\Data\MediaResourceInterface $value): void;

    /**
     * Autogenerated description for getSortOrder() interface method
     *
     * @return string
     */
    public function getSortOrder(): string;

    /**
     * Autogenerated description for setSortOrder() interface method
     *
     * @param string $value
     * @return void
     */
    public function setSortOrder(string $value): void;
}
