<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for ImportProductsResponse interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ImportProductsResponseInterface
{
    /**
     * Autogenerated description for getStatus() interface method
     *
     * @return bool
     */
    public function getStatus(): bool;

    /**
     * Autogenerated description for setStatus() interface method
     *
     * @param bool $value
     * @return void
     */
    public function setStatus(bool $value): void;

    /**
     * Autogenerated description for getMessage() interface method
     *
     * @return string
     */
    public function getMessage(): string;

    /**
     * Autogenerated description for setMessage() interface method
     *
     * @param string $value
     * @return void
     */
    public function setMessage(string $value): void;
}
