<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for ImportVariantsRequest class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class ImportVariantsRequest implements ImportVariantsRequestInterface
{

    /**
     * @var array
     */
    private $variants;
    
    /**
     * @inheritdoc
     *
     * @return \Magento\CatalogStorefrontApi\Api\Data\ProductVariantImportInterface[]
     */
    public function getVariants(): array
    {
        return (array) $this->variants;
    }
    
    /**
     * @inheritdoc
     *
     * @param \Magento\CatalogStorefrontApi\Api\Data\ProductVariantImportInterface[] $value
     * @return void
     */
    public function setVariants(array $value): void
    {
        $this->variants = $value;
    }
}
