<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

interface ImportCategoriesResponseInterface
{

        /**
     * @return bool
     */
    public function getStatus(): bool;
    
    /**
     * @param bool $value
     * @return void
     */
    public function setStatus(bool $value): void;

    /**
     * @return string
     */
    public function getMessage(): string;
    
    /**
     * @param string $value
     * @return void
     */
    public function setMessage(string $value): void;
}
