<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for Link interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface LinkInterface
{
    /**
     * Autogenerated description for getProductId() interface method
     *
     * @return string
     */
    public function getProductId(): string;

    /**
     * Autogenerated description for setProductId() interface method
     *
     * @param string $value
     * @return void
     */
    public function setProductId(string $value): void;

    /**
     * Autogenerated description for getPosition() interface method
     *
     * @return int
     */
    public function getPosition(): int;

    /**
     * Autogenerated description for setPosition() interface method
     *
     * @param int $value
     * @return void
     */
    public function setPosition(int $value): void;

    /**
     * Autogenerated description for getType() interface method
     *
     * @return string
     */
    public function getType(): string;

    /**
     * Autogenerated description for setType() interface method
     *
     * @param string $value
     * @return void
     */
    public function setType(string $value): void;

    /**
     * Autogenerated description for getQty() interface method
     *
     * @return float
     */
    public function getQty(): float;

    /**
     * Autogenerated description for setQty() interface method
     *
     * @param float $value
     * @return void
     */
    public function setQty(float $value): void;
}
