<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

use Magento\Framework\ObjectManagerInterface;

/**
 * Autogenerated description for MediaGalleryItem class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.UnusedPrivateField)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
final class MediaGalleryItemArrayMapper
{
    /**
     * @var mixed
     */
    private $data;

    /**
     * @var ObjectManagerInterface
     */
    private $objectManager;

    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
    }

    /**
    * Convert the DTO to the array with the data
    *
    * @param MediaGalleryItem $dto
    * @return array
    */
    public function convertToArray(MediaGalleryItem $dto)
    {
        $result = [];
        $result["url"] = $dto->getUrl();
        $result["label"] = $dto->getLabel();
        $result["media_type"] = $dto->getMediaType();
        $result["position"] = $dto->getPosition();
        if ($dto->getVideoContent() !== null) {
            $result["video_content"] = $this->objectManager->get(\Magento\CatalogStorefrontApi\Api\Data\VideoArrayMapper::class)
                ->convertToArray($dto->getVideoContent());
        }
        return $result;
    }
}
