<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

final class Price implements PriceInterface
{
    /**
     * @var float
     */
    private $regular;
    /**
     * @var array
     */
    private $regularAdjustments;
    /**
     * @var float
     */
    private $final;
    /**
     * @var array
     */
    private $finalAdjustments;


    /**
     * @return float
     */
    public function getRegular(): float
    {
        return (float) $this->regular;
    }
    
    /**
     * @param float $value
     * @return void
     */
    public function setRegular(float $value): void
    {
        $this->regular = $value;
    }

    /**
     * @return \Magento\CatalogStorefrontApi\Api\Data\AdjustmentInterface[]
     */
    public function getRegularAdjustments(): array
    {
        return (array) $this->regularAdjustments;
    }
    
    /**
     * @param \Magento\CatalogStorefrontApi\Api\Data\AdjustmentInterface[] $value
     * @return void
     */
    public function setRegularAdjustments(array $value): void
    {
        $this->regularAdjustments = $value;
    }

    /**
     * @return float
     */
    public function getFinal(): float
    {
        return (float) $this->final;
    }
    
    /**
     * @param float $value
     * @return void
     */
    public function setFinal(float $value): void
    {
        $this->final = $value;
    }

    /**
     * @return \Magento\CatalogStorefrontApi\Api\Data\AdjustmentInterface[]
     */
    public function getFinalAdjustments(): array
    {
        return (array) $this->finalAdjustments;
    }
    
    /**
     * @param \Magento\CatalogStorefrontApi\Api\Data\AdjustmentInterface[] $value
     * @return void
     */
    public function setFinalAdjustments(array $value): void
    {
        $this->finalAdjustments = $value;
    }
}
