<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

final class ProductsGetRequest implements ProductsGetRequestInterface
{
    /**
     * @var string
     */
    private $ids;
    /**
     * @var string
     */
    private $store;
    /**
     * @var string
     */
    private $attributeCodes;


    /**
     * @return string
     */
    public function getIds(): string
    {
        return (string) $this->ids;
    }
    
    /**
     * @param string $value
     * @return void
     */
    public function setIds(string $value): void
    {
        $this->ids = $value;
    }

    /**
     * @return string
     */
    public function getStore(): string
    {
        return (string) $this->store;
    }
    
    /**
     * @param string $value
     * @return void
     */
    public function setStore(string $value): void
    {
        $this->store = $value;
    }

    /**
     * @return string
     */
    public function getAttributeCodes(): string
    {
        return (string) $this->attributeCodes;
    }
    
    /**
     * @param string $value
     * @return void
     */
    public function setAttributeCodes(string $value): void
    {
        $this->attributeCodes = $value;
    }
}
