<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

interface ProductsGetRequestInterface
{

        /**
     * @return string
     */
    public function getIds(): string;
    
    /**
     * @param string $value
     * @return void
     */
    public function setIds(string $value): void;

    /**
     * @return string
     */
    public function getStore(): string;
    
    /**
     * @param string $value
     * @return void
     */
    public function setStore(string $value): void;

    /**
     * @return string
     */
    public function getAttributeCodes(): string;
    
    /**
     * @param string $value
     * @return void
     */
    public function setAttributeCodes(string $value): void;
}
