<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for ProductOption interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ProductOptionInterface
{
    /**
     * Autogenerated description for getId() interface method
     *
     * @return string
     */
    public function getId(): string;

    /**
     * Autogenerated description for setId() interface method
     *
     * @param string $value
     * @return void
     */
    public function setId(string $value): void;

    /**
     * Autogenerated description for getLabel() interface method
     *
     * @return string
     */
    public function getLabel(): string;

    /**
     * Autogenerated description for setLabel() interface method
     *
     * @param string $value
     * @return void
     */
    public function setLabel(string $value): void;

    /**
     * Autogenerated description for getSortOrder() interface method
     *
     * @return int
     */
    public function getSortOrder(): int;

    /**
     * Autogenerated description for setSortOrder() interface method
     *
     * @param int $value
     * @return void
     */
    public function setSortOrder(int $value): void;

    /**
     * Autogenerated description for getRequired() interface method
     *
     * @return bool
     */
    public function getRequired(): bool;

    /**
     * Autogenerated description for setRequired() interface method
     *
     * @param bool $value
     * @return void
     */
    public function setRequired(bool $value): void;

    /**
     * Autogenerated description for getRenderType() interface method
     *
     * @return string
     */
    public function getRenderType(): string;

    /**
     * Autogenerated description for setRenderType() interface method
     *
     * @param string $value
     * @return void
     */
    public function setRenderType(string $value): void;

    /**
     * Autogenerated description for getType() interface method
     *
     * @return string
     */
    public function getType(): string;

    /**
     * Autogenerated description for setType() interface method
     *
     * @param string $value
     * @return void
     */
    public function setType(string $value): void;

    /**
     * Autogenerated description for getValues() interface method
     *
     * @return \Magento\CatalogStorefrontApi\Api\Data\ProductOptionValueInterface[]
     */
    public function getValues(): array;

    /**
     * Autogenerated description for setValues() interface method
     *
     * @param \Magento\CatalogStorefrontApi\Api\Data\ProductOptionValueInterface[] $value
     * @return void
     */
    public function setValues(array $value): void;
}
