<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for ProductVariantImport interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ProductVariantImportInterface
{
    /**
     * Autogenerated description for getId() interface method
     *
     * @return string
     */
    public function getId(): string;

    /**
     * Autogenerated description for setId() interface method
     *
     * @param string $value
     * @return void
     */
    public function setId(string $value): void;

    /**
     * Autogenerated description for getOptionValues() interface method
     *
     * @return string[]
     */
    public function getOptionValues(): array;

    /**
     * Autogenerated description for setOptionValues() interface method
     *
     * @param string[] $value
     * @return void
     */
    public function setOptionValues(array $value): void;
}
