<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for ProductVariantRequest interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface ProductVariantRequestInterface
{
    /**
     * Autogenerated description for getProductId() interface method
     *
     * @return string
     */
    public function getProductId(): string;

    /**
     * Autogenerated description for setProductId() interface method
     *
     * @param string $value
     * @return void
     */
    public function setProductId(string $value): void;

    /**
     * Autogenerated description for getStore() interface method
     *
     * @return string
     */
    public function getStore(): string;

    /**
     * Autogenerated description for setStore() interface method
     *
     * @param string $value
     * @return void
     */
    public function setStore(string $value): void;
}
