<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for UrlRewrite interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface UrlRewriteInterface
{
    /**
     * Autogenerated description for getUrl() interface method
     *
     * @return string
     */
    public function getUrl(): string;

    /**
     * Autogenerated description for setUrl() interface method
     *
     * @param string $value
     * @return void
     */
    public function setUrl(string $value): void;

    /**
     * Autogenerated description for getParameters() interface method
     *
     * @return \Magento\CatalogStorefrontApi\Api\Data\UrlRewriteParameterInterface[]
     */
    public function getParameters(): array;

    /**
     * Autogenerated description for setParameters() interface method
     *
     * @param \Magento\CatalogStorefrontApi\Api\Data\UrlRewriteParameterInterface[] $value
     * @return void
     */
    public function setParameters(array $value): void;
}
