<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

interface UrlRewriteInterface
{

        /**
     * @return string
     */
    public function getUrl(): string;
    
    /**
     * @param string $value
     * @return void
     */
    public function setUrl(string $value): void;

    /**
     * @return \Magento\CatalogStorefrontApi\Api\Data\UrlRewriteParameterInterface[]
     */
    public function getParameters(): array;
    
    /**
     * @param \Magento\CatalogStorefrontApi\Api\Data\UrlRewriteParameterInterface[] $value
     * @return void
     */
    public function setParameters(array $value): void;
}
