<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for Variant class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class Variant implements VariantInterface
{

    /**
     * @var string
     */
    private $product;

    /**
     * @var array
     */
    private $attributes;
    
    /**
     * @inheritdoc
     *
     * @return string
     */
    public function getProduct(): string
    {
        return (string) $this->product;
    }
    
    /**
     * @inheritdoc
     *
     * @param string $value
     * @return void
     */
    public function setProduct(string $value): void
    {
        $this->product = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return \Magento\CatalogStorefrontApi\Api\Data\VariantAttributeInterface[]
     */
    public function getAttributes(): array
    {
        return (array) $this->attributes;
    }
    
    /**
     * @inheritdoc
     *
     * @param \Magento\CatalogStorefrontApi\Api\Data\VariantAttributeInterface[] $value
     * @return void
     */
    public function setAttributes(array $value): void
    {
        $this->attributes = $value;
    }
}
