<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\CatalogStorefrontApi\Api\Data;

/**
 * Autogenerated description for VideoItem interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface VideoItemInterface
{
    /**
     * Autogenerated description for getVideoProvider() interface method
     *
     * @return string
     */
    public function getVideoProvider(): string;

    /**
     * Autogenerated description for setVideoProvider() interface method
     *
     * @param string $value
     * @return void
     */
    public function setVideoProvider(string $value): void;

    /**
     * Autogenerated description for getVideoUrl() interface method
     *
     * @return string
     */
    public function getVideoUrl(): string;

    /**
     * Autogenerated description for setVideoUrl() interface method
     *
     * @param string $value
     * @return void
     */
    public function setVideoUrl(string $value): void;

    /**
     * Autogenerated description for getVideoTitle() interface method
     *
     * @return string
     */
    public function getVideoTitle(): string;

    /**
     * Autogenerated description for setVideoTitle() interface method
     *
     * @param string $value
     * @return void
     */
    public function setVideoTitle(string $value): void;

    /**
     * Autogenerated description for getVideoDescription() interface method
     *
     * @return string
     */
    public function getVideoDescription(): string;

    /**
     * Autogenerated description for setVideoDescription() interface method
     *
     * @param string $value
     * @return void
     */
    public function setVideoDescription(string $value): void;

    /**
     * Autogenerated description for getVideoMetadata() interface method
     *
     * @return string
     */
    public function getVideoMetadata(): string;

    /**
     * Autogenerated description for setVideoMetadata() interface method
     *
     * @param string $value
     * @return void
     */
    public function setVideoMetadata(string $value): void;

    /**
     * Autogenerated description for getMediaType() interface method
     *
     * @return string
     */
    public function getMediaType(): string;

    /**
     * Autogenerated description for setMediaType() interface method
     *
     * @param string $value
     * @return void
     */
    public function setMediaType(string $value): void;
}
