<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto

namespace Magento\CatalogStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.catalogStorefrontApi.proto.Category</code>
 */
class Category extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string path = 2;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>int32 position = 3;</code>
     */
    protected $position = 0;
    /**
     * Generated from protobuf field <code>int32 level = 4;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>int32 children_count = 5;</code>
     */
    protected $children_count = 0;
    /**
     * Generated from protobuf field <code>string name = 6;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string display_mode = 7;</code>
     */
    protected $display_mode = '';
    /**
     * Generated from protobuf field <code>string default_sort_by = 8;</code>
     */
    protected $default_sort_by = '';
    /**
     * Generated from protobuf field <code>string url_key = 9;</code>
     */
    protected $url_key = '';
    /**
     * Generated from protobuf field <code>string url_path = 10;</code>
     */
    protected $url_path = '';
    /**
     * Generated from protobuf field <code>bool is_active = 11;</code>
     */
    protected $is_active = false;
    /**
     * Generated from protobuf field <code>bool is_anchor = 12;</code>
     */
    protected $is_anchor = false;
    /**
     * Generated from protobuf field <code>bool include_in_menu = 13;</code>
     */
    protected $include_in_menu = false;
    /**
     * Generated from protobuf field <code>repeated string available_sort_by = 14;</code>
     */
    private $available_sort_by;
    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.Breadcrumb breadcrumbs = 15;</code>
     */
    private $breadcrumbs;
    /**
     * Generated from protobuf field <code>string description = 16;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>string canonical_url = 17;</code>
     */
    protected $canonical_url = '';
    /**
     * Generated from protobuf field <code>int64 product_count = 18;</code>
     */
    protected $product_count = 0;
    /**
     * Generated from protobuf field <code>repeated string children = 19;</code>
     */
    private $children;
    /**
     * Generated from protobuf field <code>string image = 20;</code>
     */
    protected $image = '';
    /**
     * Generated from protobuf field <code>string parent_id = 21;</code>
     */
    protected $parent_id = '';
    /**
     * Generated from protobuf field <code>string meta_title = 22;</code>
     */
    protected $meta_title = '';
    /**
     * Generated from protobuf field <code>string meta_description = 23;</code>
     */
    protected $meta_description = '';
    /**
     * Generated from protobuf field <code>string meta_keywords = 24;</code>
     */
    protected $meta_keywords = '';
    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.Attribute attributes = 50;</code>
     */
    private $attributes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $path
     *     @type int $position
     *     @type int $level
     *     @type int $children_count
     *     @type string $name
     *     @type string $display_mode
     *     @type string $default_sort_by
     *     @type string $url_key
     *     @type string $url_path
     *     @type bool $is_active
     *     @type bool $is_anchor
     *     @type bool $include_in_menu
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $available_sort_by
     *     @type \Magento\CatalogStorefrontApi\Proto\Breadcrumb[]|\Google\Protobuf\Internal\RepeatedField $breadcrumbs
     *     @type string $description
     *     @type string $canonical_url
     *     @type int|string $product_count
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $children
     *     @type string $image
     *     @type string $parent_id
     *     @type string $meta_title
     *     @type string $meta_description
     *     @type string $meta_keywords
     *     @type \Magento\CatalogStorefrontApi\Proto\Attribute[]|\Google\Protobuf\Internal\RepeatedField $attributes
     * }
     */
    public function __construct($data = null)
    {
        \Magento\CatalogStorefrontApi\Metadata\Catalog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 position = 3;</code>
     * @return int
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Generated from protobuf field <code>int32 position = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkInt32($var);
        $this->position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 level = 4;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int32 level = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 children_count = 5;</code>
     * @return int
     */
    public function getChildrenCount()
    {
        return $this->children_count;
    }

    /**
     * Generated from protobuf field <code>int32 children_count = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setChildrenCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->children_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 6;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string display_mode = 7;</code>
     * @return string
     */
    public function getDisplayMode()
    {
        return $this->display_mode;
    }

    /**
     * Generated from protobuf field <code>string display_mode = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayMode($var)
    {
        GPBUtil::checkString($var, true);
        $this->display_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string default_sort_by = 8;</code>
     * @return string
     */
    public function getDefaultSortBy()
    {
        return $this->default_sort_by;
    }

    /**
     * Generated from protobuf field <code>string default_sort_by = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDefaultSortBy($var)
    {
        GPBUtil::checkString($var, true);
        $this->default_sort_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url_key = 9;</code>
     * @return string
     */
    public function getUrlKey()
    {
        return $this->url_key;
    }

    /**
     * Generated from protobuf field <code>string url_key = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUrlKey($var)
    {
        GPBUtil::checkString($var, true);
        $this->url_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url_path = 10;</code>
     * @return string
     */
    public function getUrlPath()
    {
        return $this->url_path;
    }

    /**
     * Generated from protobuf field <code>string url_path = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUrlPath($var)
    {
        GPBUtil::checkString($var, true);
        $this->url_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_active = 11;</code>
     * @return bool
     */
    public function getIsActive()
    {
        return $this->is_active;
    }

    /**
     * Generated from protobuf field <code>bool is_active = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsActive($var)
    {
        GPBUtil::checkBool($var);
        $this->is_active = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_anchor = 12;</code>
     * @return bool
     */
    public function getIsAnchor()
    {
        return $this->is_anchor;
    }

    /**
     * Generated from protobuf field <code>bool is_anchor = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAnchor($var)
    {
        GPBUtil::checkBool($var);
        $this->is_anchor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool include_in_menu = 13;</code>
     * @return bool
     */
    public function getIncludeInMenu()
    {
        return $this->include_in_menu;
    }

    /**
     * Generated from protobuf field <code>bool include_in_menu = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setIncludeInMenu($var)
    {
        GPBUtil::checkBool($var);
        $this->include_in_menu = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string available_sort_by = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAvailableSortBy()
    {
        return $this->available_sort_by;
    }

    /**
     * Generated from protobuf field <code>repeated string available_sort_by = 14;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAvailableSortBy($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->available_sort_by = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.Breadcrumb breadcrumbs = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBreadcrumbs()
    {
        return $this->breadcrumbs;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.Breadcrumb breadcrumbs = 15;</code>
     * @param \Magento\CatalogStorefrontApi\Proto\Breadcrumb[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBreadcrumbs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Magento\CatalogStorefrontApi\Proto\Breadcrumb::class);
        $this->breadcrumbs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 16;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, true);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string canonical_url = 17;</code>
     * @return string
     */
    public function getCanonicalUrl()
    {
        return $this->canonical_url;
    }

    /**
     * Generated from protobuf field <code>string canonical_url = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setCanonicalUrl($var)
    {
        GPBUtil::checkString($var, true);
        $this->canonical_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 product_count = 18;</code>
     * @return int|string
     */
    public function getProductCount()
    {
        return $this->product_count;
    }

    /**
     * Generated from protobuf field <code>int64 product_count = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProductCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->product_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string children = 19;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * Generated from protobuf field <code>repeated string children = 19;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChildren($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->children = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string image = 20;</code>
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Generated from protobuf field <code>string image = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkString($var, true);
        $this->image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parent_id = 21;</code>
     * @return string
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Generated from protobuf field <code>string parent_id = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setParentId($var)
    {
        GPBUtil::checkString($var, true);
        $this->parent_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string meta_title = 22;</code>
     * @return string
     */
    public function getMetaTitle()
    {
        return $this->meta_title;
    }

    /**
     * Generated from protobuf field <code>string meta_title = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setMetaTitle($var)
    {
        GPBUtil::checkString($var, true);
        $this->meta_title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string meta_description = 23;</code>
     * @return string
     */
    public function getMetaDescription()
    {
        return $this->meta_description;
    }

    /**
     * Generated from protobuf field <code>string meta_description = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setMetaDescription($var)
    {
        GPBUtil::checkString($var, true);
        $this->meta_description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string meta_keywords = 24;</code>
     * @return string
     */
    public function getMetaKeywords()
    {
        return $this->meta_keywords;
    }

    /**
     * Generated from protobuf field <code>string meta_keywords = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setMetaKeywords($var)
    {
        GPBUtil::checkString($var, true);
        $this->meta_keywords = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.Attribute attributes = 50;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.Attribute attributes = 50;</code>
     * @param \Magento\CatalogStorefrontApi\Proto\Attribute[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Magento\CatalogStorefrontApi\Proto\Attribute::class);
        $this->attributes = $arr;

        return $this;
    }
}
