<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto

namespace Magento\CatalogStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.catalogStorefrontApi.proto.Option</code>
 */
class Option extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string type = 2;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.OptionValue values = 4;</code>
     */
    private $values;
    /**
     * No meaning for configurable
     *
     * Generated from protobuf field <code>bool allowMulti = 5;</code>
     */
    protected $allowMulti = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $type
     *     @type string $name
     *     @type \Magento\CatalogStorefrontApi\Proto\OptionValue[]|\Google\Protobuf\Internal\RepeatedField $values
     *     @type bool $allowMulti
     *           No meaning for configurable
     * }
     */
    public function __construct($data = null)
    {
        \Magento\CatalogStorefrontApi\Metadata\Catalog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, true);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.OptionValue values = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.OptionValue values = 4;</code>
     * @param \Magento\CatalogStorefrontApi\Proto\OptionValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Magento\CatalogStorefrontApi\Proto\OptionValue::class);
        $this->values = $arr;

        return $this;
    }

    /**
     * No meaning for configurable
     *
     * Generated from protobuf field <code>bool allowMulti = 5;</code>
     * @return bool
     */
    public function getAllowMulti()
    {
        return $this->allowMulti;
    }

    /**
     * No meaning for configurable
     *
     * Generated from protobuf field <code>bool allowMulti = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowMulti($var)
    {
        GPBUtil::checkBool($var);
        $this->allowMulti = $var;

        return $this;
    }
}
