<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto

namespace Magento\CatalogStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.catalogStorefrontApi.proto.OptionValue</code>
 */
class OptionValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string value = 2;</code>
     */
    protected $value = '';
    /**
     * Null for configurable, possibly provides price for bundle options
     *
     * Generated from protobuf field <code>.magento.catalogStorefrontApi.proto.Price minimumPrice = 3;</code>
     */
    protected $minimumPrice = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $value
     *     @type \Magento\CatalogStorefrontApi\Proto\Price $minimumPrice
     *           Null for configurable, possibly provides price for bundle options
     * }
     */
    public function __construct($data = null)
    {
        \Magento\CatalogStorefrontApi\Metadata\Catalog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, true);
        $this->value = $var;

        return $this;
    }

    /**
     * Null for configurable, possibly provides price for bundle options
     *
     * Generated from protobuf field <code>.magento.catalogStorefrontApi.proto.Price minimumPrice = 3;</code>
     * @return \Magento\CatalogStorefrontApi\Proto\Price
     */
    public function getMinimumPrice()
    {
        return $this->minimumPrice;
    }

    /**
     * Null for configurable, possibly provides price for bundle options
     *
     * Generated from protobuf field <code>.magento.catalogStorefrontApi.proto.Price minimumPrice = 3;</code>
     * @param \Magento\CatalogStorefrontApi\Proto\Price $var
     * @return $this
     */
    public function setMinimumPrice($var)
    {
        GPBUtil::checkMessage($var, \Magento\CatalogStorefrontApi\Proto\Price::class);
        $this->minimumPrice = $var;

        return $this;
    }
}
