<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto

namespace Magento\CatalogStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.catalogStorefrontApi.proto.ProductVariant</code>
 */
class ProductVariant extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 2;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>repeated string option_value_id = 1;</code>
     */
    private $option_value_id;
    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.Price price = 3;</code>
     */
    private $price;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $option_value_id
     *     @type \Magento\CatalogStorefrontApi\Proto\Price[]|\Google\Protobuf\Internal\RepeatedField $price
     * }
     */
    public function __construct($data = null)
    {
        \Magento\CatalogStorefrontApi\Metadata\Catalog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string option_value_id = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOptionValueId()
    {
        return $this->option_value_id;
    }

    /**
     * Generated from protobuf field <code>repeated string option_value_id = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOptionValueId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->option_value_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.Price price = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.catalogStorefrontApi.proto.Price price = 3;</code>
     * @param \Magento\CatalogStorefrontApi\Proto\Price[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrice($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Magento\CatalogStorefrontApi\Proto\Price::class);
        $this->price = $arr;

        return $this;
    }
}
