<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto

namespace Magento\CatalogStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.catalogStorefrontApi.proto.RatingsMetadataRequest</code>
 */
class RatingsMetadataRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string rating_id = 1;</code>
     */
    protected $rating_id = '';
    /**
     * Generated from protobuf field <code>string store = 2;</code>
     */
    protected $store = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $rating_id
     *     @type string $store
     * }
     */
    public function __construct($data = null)
    {
        \Magento\CatalogStorefrontApi\Metadata\Catalog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string rating_id = 1;</code>
     * @return string
     */
    public function getRatingId()
    {
        return $this->rating_id;
    }

    /**
     * Generated from protobuf field <code>string rating_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRatingId($var)
    {
        GPBUtil::checkString($var, true);
        $this->rating_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string store = 2;</code>
     * @return string
     */
    public function getStore()
    {
        return $this->store;
    }

    /**
     * Generated from protobuf field <code>string store = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStore($var)
    {
        GPBUtil::checkString($var, true);
        $this->store = $var;

        return $this;
    }
}
