<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\SearchStorefrontApi\Api\Data;

/**
 * Autogenerated description for Sort class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class Sort implements SortInterface
{

    /**
     * @var string
     */
    private $attribute;

    /**
     * @var string
     */
    private $title;
    
    /**
     * @inheritdoc
     *
     * @return string
     */
    public function getAttribute(): string
    {
        return (string) $this->attribute;
    }
    
    /**
     * @inheritdoc
     *
     * @param string $value
     * @return void
     */
    public function setAttribute(string $value): void
    {
        $this->attribute = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return string
     */
    public function getTitle(): string
    {
        return (string) $this->title;
    }
    
    /**
     * @inheritdoc
     *
     * @param string $value
     * @return void
     */
    public function setTitle(string $value): void
    {
        $this->title = $value;
    }
}
